name = "GoAot"
version = "0.1.0"
defaultTargets = ["goaot"]
testDriver = "tests"

[[lean_exe]]
name = "goaot"
root = "Main"

[[lean_lib]]
name = "GoAot"

[[lean_lib]]
name = "Compiler"
globs = ["Compiler.+"]

[[lean_exe]]
name = "tests"
root = "Tests.Lexer"

[[lean_exe]]
name = "integration_tests"
root = "Tests.Golden"
