// Print Compiler/Unicode.lean
//
// Run: go run scripts/unicode.go
package main

import (
	"fmt"
	"unicode"
)

func table(name string, t *unicode.RangeTable) {
	fmt.Printf("private def %s : Array (Nat × Nat × Nat) := #[\n", name)
	count := 0
	entry := func(lo, hi, stride uint32) {
		if count > 0 {
			fmt.Print(", ")
		}
		if count%3 == 0 {
			fmt.Print("\n  ")
		}
		fmt.Printf("(0x%x, 0x%x, %d)", lo, hi, stride)
		count++
	}
	for _, r := range t.R16 {
		entry(uint32(r.Lo), uint32(r.Hi), uint32(r.Stride))
	}
	for _, r := range t.R32 {
		entry(r.Lo, r.Hi, r.Stride)
	}
	fmt.Print("\n]\n\n")
}

func main() {
	fmt.Printf(`module

/- Generated by scripts/unicode.go from Go's unicode.L and unicode.Nd (Unicode %s).
Do not edit the tables by hand. https://go.dev/src/unicode/tables.go -/

namespace GoAot.Unicode

`, unicode.Version)
	table("letters", unicode.L)
	table("digits", unicode.Nd)
	fmt.Print(`private def contains (ranges : Array (Nat × Nat × Nat)) (c : Char) : Bool := Id.run do
  let n := c.toNat
  let mut lo := 0
  let mut hi := ranges.size
  while lo < hi do
    let mid := (lo + hi) / 2
    let (first, last, stride) := ranges[mid]!
    if n < first then hi := mid
    else if n > last then lo := mid + 1
    else return (n - first) % stride == 0
  return false

public def isLetter (c : Char) : Bool := contains letters c
public def isDigit (c : Char) : Bool := contains digits c

end GoAot.Unicode
`)
}
