name: Lean Action CI

on:
  push:
    paths:
      - '**.lean'
      - 'Tests/**'
      - 'lakefile.toml'
      - 'lake-manifest.json'
      - 'lean-toolchain'
      - '.github/workflows/lean_action_ci.yml'
  pull_request:
    paths:
      - '**.lean'
      - 'Tests/**'
      - 'lakefile.toml'
      - 'lake-manifest.json'
      - 'lean-toolchain'
      - '.github/workflows/lean_action_ci.yml'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - uses: leanprover/lean-action@v1
